function chkSim___tg_s02_Geometry___02_Indices___Plot_001(sel_atl,sim_geo_cort)
    hold on
    tmp_colorBar = lines(length(sim_geo_cort.lstROIs));
    for ii = 1:length(sim_geo_cort.lstROIs)
        trisurf(                      ...
            sel_atl.tri(sim_geo_cort.indROIs(ii).triNum00,:),...
            sel_atl.pnt(:,1)-0.1*sel_atl.vn1(:,1),  ...
            sel_atl.pnt(:,2)-0.1*sel_atl.vn1(:,2),  ...
            sel_atl.pnt(:,3)-0.1*sel_atl.vn1(:,3),  ...
            'facealpha',0.2,                            ...
            'facecolor',tmp_colorBar(ii,:),             ...
            'edgecolor',tmp_colorBar(ii,:),             ...
            'edgealpha',0.4);
        hold on
    end
    ccrender([-160,160],'finish','matte')

%    caxis([1 length(sim_geo_cort.lstROIs)]);
%    colormap(tmp_colorBar)
%    colorbar
end
